/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseChart: typeof import('./src/components/BaseChart.vue')['default']
    BaseLoading: typeof import('./src/components/BaseLoading.vue')['default']
    ChatHeader: typeof import('./src/components/ai-chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/ai-chat/ChatInput.vue')['default']
    ChatMessageList: typeof import('./src/components/ai-chat/ChatMessageList.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    FloatAIQA: typeof import('./src/components/FloatAIQA.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilterBar: typeof import('./src/components/SearchFilterBar.vue')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
    TableCard: typeof import('./src/components/TableCard.vue')['default']
  }
}
